const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("glove", {
  ready: () => ipcRenderer.send("ui-ready"),
  navigate: (text) => ipcRenderer.send("navigate", text),
  back: () => ipcRenderer.send("back"),
  forward: () => ipcRenderer.send("forward"),
  reload: () => ipcRenderer.send("reload"),
  stop: () => ipcRenderer.send("stop"),
  home: () => ipcRenderer.send("home"),
  newTab: () => ipcRenderer.send("new-tab"),
  closeTab: (id) => ipcRenderer.send("close-tab", id),
  selectTab: (id) => ipcRenderer.send("select-tab", id),
  menu: () => ipcRenderer.send("menu"),
  togglePicker: () => ipcRenderer.send("toggle-picker"),
  chooseEngine: (id) => ipcRenderer.send("choose-engine", id),
  suggest: (text) => ipcRenderer.send("suggest", text),
  onSuggest: (callback) => ipcRenderer.on("suggest", (_event, list) => callback(list)),
  imageSearch: () => ipcRenderer.send("image-search"),
  voiceStart: () => ipcRenderer.send("voice-start"),
  voiceStop: () => ipcRenderer.send("voice-stop"),
  onVoice: (callback) => ipcRenderer.on("voice-text", (_event, text) => callback(text)),
  onVoiceOpen: (callback) => ipcRenderer.on("voice-open", () => callback()),
  extensions: () => ipcRenderer.invoke("extensions-list"),
  openExtension: (id) => ipcRenderer.send("extension-open", id),
  removeExtension: (id) => ipcRenderer.send("extension-remove", id),
  onExtensions: (callback) => ipcRenderer.on("extensions-changed", () => callback()),
  dismissUpdate: () => ipcRenderer.send("update-dismiss"),
  onUpdate: (callback) => ipcRenderer.on("update", (_event, state) => callback(state)),
  find: (text, again) => ipcRenderer.send("find", text, !!again),
  stopFind: () => ipcRenderer.send("stop-find"),
  chromeHeight: (height) => ipcRenderer.send("chrome-height", height),
  window: (action) => ipcRenderer.send("window", action),
  onState: (callback) => ipcRenderer.on("state", (_event, state) => callback(state))
});
